### ISSUE TITLE
根据返回200状态码并不能完全筛选出可用代理

### ISSUE THREAD

**Issue by xdoer** [kongtianyi/freeProxySpider#1]
运行了你的代码，筛选了的代理，将代理设置到浏览器代理中，点击一些链接进行测试，有的显示网络错误(这个不知道为什么)，有的则重定向到有道首页。。。

想了半天，想到一个解决办法 : 将代码中尝试请求的URL改为一个返回1的URL(可以在自己服务器上构造一个)，判断代理可用条件中，加上判断返回内容是否为1即可。

ps：自己做的小项目[HttpProxy](http://httpproxy.docmobile.cn)，参考了大佬部分代码。

**Comment by kongtianyi** [comment]
是的，我也遇到了类似问题，后来是取网上一些静态资源的前几个字符进行判断的，跟阁下想的一样。心疼疆内网民（手动滑稽）
